
CPU_DATA = "CPU_DATA"
CPU_NAME = "ID"

TASK_DATA = "\tTASK "
TASK_CPU = "CPU_ID"
TASK_PRIORITY = "PRIORITY"
TASK_RESOURCE = "RESOURCE"

SPIN_PRIO = "EE_th_spin_prio"
GLOBAL_TASK_ID = "GlobalTaskID"

THREAD_TOS = "EE_hal_thread_tos"
SYSTEM_TOS = "EE_nios2_system_tos"
WARN_STR = "\t\n/*!!!THE STACK INFORMATION HAS BEEN MODIFIED BY FLEXTOOL!!*/\n"
